export default Object.freeze({
  // login page
  GET_POSITION_LIST: 'getPositionList',
  GET_LOGIN_HISTORY: 'getLoginHistory',

  // WBC classification
  GET_WBC_CLASS_LIST: 'getWbcClassList',
  GET_WBC_CLASS_LIST_ALL: 'getWbcClassListAll',
  GET_WBC_TOTAL_COUNT: 'getWbcTotalCount',
  UPDATE_WBC_COUNT: 'updateWbcCount',
  GET_WBC_COUNT: 'getWbcCount',
  GET_RBC_COUNT: 'getRbcCount',
  UPDATE_DEGREE: 'updateDegree',
  INIT_WBC_COUNT: 'initWbcCount',
  INIT_RBC_DEGREE: 'initRbcDegree',
  UPDATE_WBC_COMMENT: 'updateWbcComment',
  GET_WBC_INFO: 'getWbcInfo',
  SET_WBC_IMAGE_HIST: 'setWbcImageHist',
  GET_WBC_IMAGE_HIST: 'getWbcImageHist',
  INIT_WBC_IMAGE_HIST: 'initWbcImageHist',
  INSERT_WBC_CLASSIFICATION: 'insertWbcClassification',
  INSERT_BM_CLASSIFICATION: 'insertBmClassification',
  SET_WBC_CUSTOM_LIST: 'setWbcClassList',
  UPDATE_HOT_KEYS: 'updateHotKeys',
  UPDATE_HOT_KEYS_WBC_CUSTOM: 'updateHotKeysWbcCustom',
  UPDATE_BM_HOT_KEYS: 'updateBmHotKeys',

  // 집계
  GET_WBC_MODIFY_LIST: 'getWbcModifyList',
  GET_BM_MODIFY_LIST: 'getBmModifyList',

  // RBC classification
  GET_RBC_CLASS_LIST: 'getRbcClassList',
  GET_MALARIA_COUNT: 'getMalariaCount',
  UPDATE_MALARIA_COUNT: 'updateMalariaCount',
  UPDATE_RBC_COMMENT: 'updateRbcComment',
  GET_RBC_BRIGHTNESS_SLIDE_VALUE: 'getRbcBrightnessSlideValue',
  GET_RBC_RED_VALUE: 'getRbcRedValue',
  GET_RBC_GREEN_VALUE: 'getRbcGreenValue',
  GET_RBC_BLUE_VALUE: 'getRbcBlueValue',
  SET_RBC_BRIGHTNESS_SLIDE_VALUE: 'setRbcBrightnessSlideValue',
  SET_RBC_RED_VALUE: 'setRbcRedValue',
  SET_RBC_GREEN_VALUE: 'setRbcGreenValue',
  SET_RBC_BLUE_VALUE: 'setRbcBlueValue',
  SET_RBC_SHAPE: 'setRbcShape',
  GET_RBC_SHAPE: 'getRbcShape',
  SET_RBC_PLATELET: 'setRbcPlatelet',
  GET_RBC_PLATELET: 'getRbcPlatelet',
  SET_RBC_INCLUSION: 'setRbcInclusion',
  GET_RBC_INCLUSION: 'getRbcInclusion',

  SET_CLASSIFICATION: 'setClassification',
  GET_CLASSIFICATION_ITEM: 'getClassificationItem',
  SET_CLASSIFICATION_ITEM: 'setClassificationItem',

  UPDATE_RBC_CLASSIFICATION: 'updateRbcClassificatin',
  SELECT_RBC_DEGREE: 'selectRbcDegree',
  UPDATE_RBC_DEGREE: 'updateRbcDegree',

  // Test page
  SET_TEST_LIST: 'setTestList',
  GET_TEST_LIST: 'getTestList',
  GET_TEST_RESULT: 'getTestResult',
  GET_RBC_FIELDS: 'getRbcFields',
  GET_WBC_FIELDS: 'getWbcFields',
  GET_RBC_ITEMS: 'getRbcItems',
  GET_WBC_ITEMS: 'getWbcItems',
  UPDATE_RBC_DEGREE: 'updateRbcDegree',
  INIT_OIL_COUNT: 'initOilCount',
  UPDATE_RESULT: 'updateResult',
  UPDATE_RUNNING_STATE: 'updateRunningState',
  GET_ORDER_LIST: 'getOrderList',
  SET_ORDER_LIST: 'setOrderList',
  UPDATE_ORDER_LIST: 'updateOrderList',
  INIT_ORDER_LIST: 'initOrderList',
  GET_TEST_RESULT_ALL: 'getTestResultAll',
  GET_SEARCH_OPTIONS: 'getSearchOptions',
  UPDATE_SEARCH_OPTIONS: 'updateSearchOption',
  SET_TEST_HISTORY: 'setTestHistory',
  GET_TEST_HISTORY_LIST: 'getTestHistoryList',
  ALL_TEST_HISTORY_LIST: 'allTestHistoryList',
  SEARCH_TEST_HISTORY_LIST: 'searchTestHistoryList',
  UPDATE_TEST_HISTORY: 'updateTestHistory',
  GET_TEST_HISTORY: 'getTestHistory',
  DELETE_TEST_HISTORY: 'deleteTestHistory',
  DELETE_TEST_HISTORY_ONE: 'deleteTestHistoryOne',
  UPDATE_SIGNED_STATE: 'updateSignedState',
  UPDATE_TEST_HISTORY_WBC_INFO: 'updateTestHistoryWbcInfo',
  GET_RBC_COMMENT: 'getRbcComment',
  GET_WBC_COMMENT: 'getWbcComment',
  GET_RUNNING_INTERVAL_ID: 'getRunningIntervalId',
  SET_RUNNING_INTERVAL_ID: 'setRuningIntervalId',
  UPDATE_TIMER: 'updateWorkingTimer',
  GET_TIMER: 'getWorkingTimer',
  SET_TIMER: 'setWorkingTimer',
  SET_WORKING_INTERVAL_ID: 'setWorkingIntervalId',
  GET_WORKING_INTERVAL_ID: 'getWorkingIntervalId',
  GET_RUNNING_STATE: 'getRunningState',
  UPDATE_BM_CELL_COUNT: 'updateBmCellCount',
  INIT_BM_CELL_COUNT: 'initBmCellCount',
  GET_BM_CELL: 'getBmCell',
  SET_USER_STOP: 'setUserStop',
  GET_USER_STOP: 'getUserStop',
  SET_WBC_CELL_POSITION: 'setWbcCellPosition',
  GET_WBC_CELL_POSITION: 'getWbcCellPosition',
  GET_PB_SMEAR: 'getPbSmear',
  GET_TEST_HISTORY_PREV: 'getTestHistoryPrev',
  GET_TEST_HISTORY_NEXT: 'getTestHistoryNext',
  GET_DIAG_WBC_DETAIL: 'getDiagWbcDetail',

  // Favorite
  GET_FAVORITE_LIST: 'getFavoriteList',
  GET_FAVORITE: 'getFavorite',
  ADD_FAVORITE: 'addFavorite',
  SET_FAVORITE: 'setFavorite',
  REMOVE_FAVORITE: 'removeFavorite',
  UPDATE_FAVORITE: 'updateFavorite',

  // Work List
  SET_WORK_LIST: 'setWorkList',
  GET_WORK_LIST: 'getWorkList',
  INIT_WORK_LIST: 'initWorkList',
  DELETE_WORK_LIST: 'deleteWorkList',
  UPDATE_WORK_LIST: 'updateWorkList',
  UPDATE_WORK_LIST_BM: 'updateWorkListBm',
  UPDATE_SIGNED_WORK_LIST: 'updateSignedWorkList',
  UPDATE_RBC_COMMENT: 'updateRbcComment',
  UPDATE_WBC_COMMENT: 'updateWbcComment',
  UPDATE_BM_COMMENT: 'updateBmComment',
  UPDATE_SELECT_ORDER_ID: 'updateSelectOrderId',
  GET_SELECT_ORDER_ID: 'getSelectOrderId',
  ADD_WORK_LIST: 'addWorkList',
  GET_RBC_COUNT: 'getRbcCount',

  // Order
  GET_ORDER_LIST_BM: 'getOrderListBm',
  UPDATE_SELECT_STATE: 'updateSelectState',
  SET_ORDER_LIST_BM: 'setOrderListBm',
  DELETE_ORDER_LIST_BM: 'deleteOrderListBm',
  UPDATE_ORDER_LIST_BM: 'updateOrderListBm',
  UPDATE_ORDER_STATE: 'updateOrderState',
  UPDATE_ORDER_BM: 'updateOrderBm',
  ADD_ORDER_CASSET: 'addOrderCasset',
  GET_BM_CELL_CLASSIFICATION: 'getBmcellClassification',
  UPDATE_ORDER: 'updateOrder',

  // Settings
  SET_IS_NS_NB_INTEGRATION: 'setIsNsNbIntegration',
  GET_IS_NS_NB_INTEGRATION: 'getIsNsNbIntegration',
  SET_IS_CBC_SHOW: 'setIsCbcShow',
  GET_IS_CBC_SHOW: 'getIsCbcShow',
  SET_SITE_CD: 'setSiteCd',
  GET_SITE_CD: 'getSiteCd',
  SET_WBC_REPORT_PRINT: 'setWbcReportPrint',
  GET_WBC_REPORT_PRINT: 'getWbcReportPrint',
  SET_BM_REPORT_PRINT: 'setBmReportPrint',
  GET_BM_REPORT_PRINT: 'getBmReportPrint',
  SELECT_WBC_CUSTOM_CLASS: 'selectWbcCustomClass',
  SELECT_WBC_HOT_KEY: 'selectWbcHotKey',
  SELECT_BM_HOT_KEY: 'selectBmHotKey',
  UPDATE_LIS_CODE: 'updateLisCode',
  UPDATE_CBC_CODE: 'updateCbcCode',
  UPDATE_LIS_CONN_PATH: 'updateLisConnPath',
  SELECT_LIS_CODE: 'selectLisCode',
  SELECT_CBC_CODE: 'selectCbcCode',
  SELECT_LIS_CONN_PATH: 'selectLisConnPath',
  GET_BACKUP_LIST: 'getBackupList',
  RESTORE_BACKUP_DATA: 'restoreBackupData',
  DELETE_BACKUP_DATA: 'deleteBackupData',
  GET_NORMAL_RANGE: 'getNormalRange',
  UPDATE_NORMAL_RANGE: 'updateNormalRange',
  SET_WBC_NORMAL_RANGE: 'setWbcNormalRange',
  GET_WBC_NORMAL_RANGE: 'getWbcNormalRange',
  RESET_NORMAL_RANGE: 'resetNormalRange',
  SET_BM_NORMAL_RANGE: 'setBmNormalRange',
  GET_BM_NORMAL_RANGE: 'getBmNormalRange',
  SELECT_INHA_LIS_DATA: 'selectInhaLisData',

  // Common
  GET_CURRENT_USER: 'getCurrentUser',
  GET_SETTINGS: 'getSettings',
  UPDATE_RUNNING_PATH: 'updateRunningPath',
  UPDATE_RESULT_PATH_WBC: 'updateResultPathWbc',
  UPDATE_RESULT_PATH_RBC: 'updateResultPathRbc',
  UPDATE_BARCODE_PATH: 'updateBarcodePath',
  GET_SYSTEM_TIME_ID: 'getSystemTimeId',
  SET_SYSTEM_TIME_ID: 'setSystemTimeId',
  GET_USER: 'getUser',
  UPDATE_REMEMBER_STATE: 'updateRememberState',
  SET_CURRENT_USER: 'setCurrentUser',
  UPDATE_ROOT_PATH: 'updateRootPath',
  GET_FILE_FILTER: 'getFileFilter',
  GET_USER_LIST: 'getUserList',
  UPDATE_ANALYSIS_TYPE: 'updateAnalysisType',
  UPDATE_RUNNING_MODE: 'updateRunningMode',
  UPDATE_USER: 'updateUser',
  DELETE_USER: 'deleteUser',
  SET_BM_IMAGE_HIST: 'setBmImageHist',
  INIT_BM_IMAGE_HIST: 'initBmImageHist',
  GET_BM_IMAGE_HIST: 'getBmImageHist',
  UPDATE_MARKER_STATE: 'updateMarkerState',
  GET_MARKER_STATE: 'getMarkerState',
  IS_REGIST_USER: 'isRegistUser',
  SET_USER: 'setUser',
  UPDATE_LOGIN_DTTM: 'updateLoginDttm',
  SET_SIZE_SLIDE_VALUE: 'setSizeSlideValue',
  SET_BRIGHTNESS_SLIDE_VALUE: 'setBrightnessSlideValue',
  GET_SIZE_SLIDE_VALUE: 'getSizeSlideValue',
  GET_BRIGHTNESS_SLIDE_VALUE: 'getBrightnessSlideValue',
  SET_IS_SHOW_MODAL_BARCODE: 'setIsShowModalBarcode',
  GET_IS_SHOW_MODAL_BARCODE: 'getIsShowModalBarcode',
  GET_RED_VALUE: 'getRedValue',
  GET_GREEN_VALUE: 'getGreenValue',
  GET_BLUE_VALUE: 'getBlueValue',
  GET_RGB_VALUE: 'getRgbValue',
  SET_RED_VALUE: 'setRedValue',
  SET_GREEN_VALUE: 'setGreenValue',
  SET_BLUE_VALUE: 'setBlueValue',
  SET_RGB_VALUE: 'setRgbValue',
  SET_DEVICE_BARCODE: 'setDeviceBarcode',
  GET_DEVICE_BARCODE: 'getDeviceBarcode',
  GET_CBC_LIST: 'getCbcList',
  GET_KUMC_CBC_PATH: 'getKumcCbcPath',
  GET_DEFAULT_RBC_DEGREE: 'getDefaultRbcDegree',
  UPDATE_CHECKED_CELL:'updateCheckedCell',

  // diagnosis
  GET_PB_TREE: 'getPbTree',
  GET_BM_TREE: 'getBmTree',
  DIAG_UPDATE_RBC_DEGREE: 'diagUpdateRbcDegree',
  DIAG_UPDATE_INPUT: 'diagUpdateInput',
  SET_PB_TREE_DATA: 'setPbTreeData',
  GET_PB_TREE_DATA: 'getPbTreeData',
  SET_BM_TREE_DATA: 'setBmTreeData',
  GET_BM_TREE_DATA: 'getBmTreeData',

  // log history
  INSERT_WBC_MODIFY_HIST: 'insetWbcModifyHist',
  GET_WBC_MODIFY_HIST: 'getWbcModifyHist',
  UPDATE_WBC_HIST_LIST: 'UPDATE_WBC_HIST_LIST',
  GET_WBC_HIST_LIST: 'getWbcHistList',
  GET_BM_HIST_LIST: 'getBmHistList',

  // Code group
  GET_COMMON_CODE_LIST: 'getCommonCodeList',
  GET_COMMON_CODE: 'getCommonCode',

  GET_CODE_LIST_USER_POSITION: '00',
  GET_CODE_LIST_USER_AUTHORIZATION: '01',
  GET_CODE_LIST_USER_CASSETE_STATE: '02',
  GET_CODE_LIST_PROCESSING_STATE: '03',
  GET_CODE_LIST_ANALYSIS_TYPE: '04',
  GET_CODE_LIST_CELL_COUNT: '05',
  GET_CODE_LIST_GENERAL_STAIN: '06',
  GET_CODE_LIST_SPECIAL_STAIN: '07',
  GET_CODE_LIST_IMMUNO_STAIN: '08',
  GET_CODE_LIST_SAMPLING_STAIN: '09',
  GET_CODE_LIST_GENDER: '10',
  GET_CODE_LIST_TEST_TYPE: '11',
  GET_CODE_SIGNED_STATE: '12',
  GET_CODE_LOG_TYPE: '13',
  GET_CODE_SLOT_STATE: '14',
  GET_STITCH_COUNT: '15',

  // event type
  EVENT_TYPE_USER: '00',
  EVENT_TYPE_SYSTEM: '01',

  // System log
  SET_EVENT_LOG: 'setEventLog',
  GET_EVENT_LOG: 'getEventLog',
  REMOVE_EVENT_LOG: 'removeEventLog',

  // Storage
  REMEMBER_PWD_KEY: 'uimdia190$^!00000000000000000000',
  REMEMBER_PWD_IV: '0000000000000000',

  // Workers
  RECEIVE_DATA_BROADCAST_CHAN: 'RECEIVE_DATA_BROADCAST_CHAN',


  // Message
  IDS_MSG_SUCCESS: 'Success',
  IDS_MSG_FAILED: 'Failed',
  IDS_MSG_OIL_REMAIN_COUNTER: 'Reset Immersion oil counter after final test or changing the Oil',
  IDS_MSG_POWEROFF: 'Shut down the system.',
  IDS_MSG_INITALIZE: 'Please execute after initialization.',
  IDS_MSG_SIGNING_COMPLETE: 'Signing is complete.',
  IDS_MSG_DELETE_THE_SELECTED_ITEMS: 'Delete the selected items?',
  IDS_MSG_ACCOUNT_CHANGED: 'Account conversion is complete.',
  IDS_MSG_DELETE_ACCOUNT: 'Are you sure you want to delete your account?',
  IDS_MSG_LOGOUT: 'Are you sure you want to logout now?',
  IDS_MSG_DUPLICATE_KEY: 'The %s key is a duplicate key.',
  IDS_MSG_HOTKEY_IN_ENGLISH: 'Please recheck the key',
  IDS_MSG_UPLOAD_LIS: 'Upload current results to LIS',

  IDS_ERROR_CHECK_ID: 'The ID must be 5-20 letters or numbers starting with the alphabet.',
  IDS_ERROR_CHECK_PASSWORD: 'The password is a combination of 6-30 digits in English, numbers.',
  IDS_ERROR_NOT_MATCHED_PASSWORD: 'Passwords do not match.',
  IDS_ERROR_SIGINUP: 'Please check the input field.',
  IDS_ERROR_SIGINUP_ALREADY_ID: 'ID already registered.',
  IDS_ERROR_LOGIN_ERROR: 'Please check your ID and password.',
  IDS_ERROR_LOGIN_ID: 'Please check your Login ID.',
  IDS_ERROR_ALREADY_RUNNING: 'Process is already running.',
  IDS_ERROR_STOP_PROCESS: 'Process is terminating.',
  IDS_ERROR_INIT_ERROR: 'Please initialize.',
  IDS_ERROR_CHECK_REQUIRED_FIELDS: 'Please check required fields',
  IDS_ERROR_CHECK_SLOT_NO: 'Please check the slot number.',
  IDS_ERROR_FAVORITE_MAX_REGIST: 'Up to 5 favorites can be registered.',
  IDS_ERROR_FAVORITE_MAX_REGIST2: 'Up to 12 favorites can be registered.',
  IDS_ERROR_SELECT_TARGETS: 'Please select a target item.',
  IDS_ERROR_ENTER_YOUR_ORDER_DETAILS: 'Please enter your order details.',
  IDS_ERROR_SELECT_A_TARGET_ITEM: 'Please select a target item.',
  IDS_ERROR_ALREADY_ADDED: 'This item has already been added.',
  IDS_ERROR_ADD_A_WORKLIST: 'Please add a worklist',
  IDS_ERROR_NO_TEST_RESULTS: 'There are no test results.',
  IDS_ERROR_FILE_CLISSIFICATION: 'File classification error',
  IDS_DOWNLOAD_COMPLETE: 'Download Complete',
  IDS_ERROR_INPUT_BM_NO: 'bmNo is a required input.',
  IDS_ERROR_PLASE_SELECT_A_PB_ITEM : 'Please select a pb item',
  IDS_SELECT_SLIDE: 'Please select a slide.',
  IDS_SIGNED_ITEMS_CANNOT_BE_MODIFIED: 'Signed items cannot be modified.',
  IDS_RECOVER_GRIPPER_CONDITION: 'Would you like to recover the gripper condition?',
  IDS_PLEASE_ENTER_END_DATE: 'Please enter the end date.',
  IDS_PLEASE_ENTER_START_DATE: 'Please enter the start date.',
  IDS_RESTART_SYSTEM: 'A new version has been downloaded. Please restart the application to apply the update.',
  IDS_PLEASE_ENTER_YOUR_BARCODE_NUMBER: 'Please enter your barcode number',
  IDS_BARCODE_REGISTRATION_SUCCESSFUL: 'Barcode registration successful',
  IDS_THIS_CARD_HAS_ALREADY_BEEN_USED: 'This card has already been used.',
  IDS_PLEASE_SELECT_A_CLASS: 'Please select a class',
  IDS_PLEASE_SELECT_A_BACKUP_DATE: 'Please select a backup date.',
  IDS_PLEASE_SELECT_A_BACKUP_PATH: 'Please select a backup path.',
  IDS_PLEASE_SELECT_A_BACKUP_FILE: 'Please select a backup file.',
  IDS_NO_DATA_FOUND: 'No data found.',
  IDS_MSG_DATA_BACKUP: 'Data from that period will be deleted. Would you like to proceed?',
  IDS_MSG_DATA_RESTORE: 'Do you want to recover your data?'
})
